USE [master]
GO
/****** Object:  Database [Variant8]    Script Date: 22.11.2025 0:11:13 ******/
CREATE DATABASE [Variant8]
GO
ALTER DATABASE [Variant8] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Variant8].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Variant8] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Variant8] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Variant8] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Variant8] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Variant8] SET ARITHABORT OFF 
GO
ALTER DATABASE [Variant8] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Variant8] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Variant8] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Variant8] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Variant8] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Variant8] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Variant8] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Variant8] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Variant8] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Variant8] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Variant8] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Variant8] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Variant8] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Variant8] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Variant8] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Variant8] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Variant8] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Variant8] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Variant8] SET  MULTI_USER 
GO
ALTER DATABASE [Variant8] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Variant8] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Variant8] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Variant8] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Variant8] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Variant8] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'Variant8', N'ON'
GO
ALTER DATABASE [Variant8] SET QUERY_STORE = ON
GO
ALTER DATABASE [Variant8] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [Variant8]
GO
/****** Object:  Table [dbo].[City]    Script Date: 22.11.2025 0:11:13 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[City](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_City] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Product]    Script Date: 22.11.2025 0:11:13 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Product](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Title] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_Product] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Product_Provider]    Script Date: 22.11.2025 0:11:13 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Product_Provider](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Provider_id] [int] NOT NULL,
	[Product_id] [int] NOT NULL,
 CONSTRAINT [PK_Product_Provider] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Provider]    Script Date: 22.11.2025 0:11:13 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Provider](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](max) NOT NULL,
	[Phone] [char](8) NOT NULL,
	[City_id] [int] NOT NULL,
 CONSTRAINT [PK_Provider] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[City] ON 
GO
INSERT [dbo].[City] ([Id], [Name]) VALUES (1, N'Москва')
GO
INSERT [dbo].[City] ([Id], [Name]) VALUES (2, N'Подольск')
GO
SET IDENTITY_INSERT [dbo].[City] OFF
GO
SET IDENTITY_INSERT [dbo].[Product] ON 
GO
INSERT [dbo].[Product] ([Id], [Title]) VALUES (1, N'Стол')
GO
INSERT [dbo].[Product] ([Id], [Title]) VALUES (2, N'Диван')
GO
INSERT [dbo].[Product] ([Id], [Title]) VALUES (3, N'Шкаф')
GO
INSERT [dbo].[Product] ([Id], [Title]) VALUES (4, N'Матрас')
GO
INSERT [dbo].[Product] ([Id], [Title]) VALUES (5, N'Стул')
GO
SET IDENTITY_INSERT [dbo].[Product] OFF
GO
SET IDENTITY_INSERT [dbo].[Product_Provider] ON 
GO
INSERT [dbo].[Product_Provider] ([Id], [Provider_id], [Product_id]) VALUES (1, 1, 1)
GO
INSERT [dbo].[Product_Provider] ([Id], [Provider_id], [Product_id]) VALUES (2, 1, 2)
GO
INSERT [dbo].[Product_Provider] ([Id], [Provider_id], [Product_id]) VALUES (3, 1, 3)
GO
INSERT [dbo].[Product_Provider] ([Id], [Provider_id], [Product_id]) VALUES (4, 2, 4)
GO
INSERT [dbo].[Product_Provider] ([Id], [Provider_id], [Product_id]) VALUES (5, 2, 5)
GO
SET IDENTITY_INSERT [dbo].[Product_Provider] OFF
GO
SET IDENTITY_INSERT [dbo].[Provider] ON 
GO
INSERT [dbo].[Provider] ([Id], [Name], [Phone], [City_id]) VALUES (1, N'Артекс', N'945-1122', 1)
GO
INSERT [dbo].[Provider] ([Id], [Name], [Phone], [City_id]) VALUES (2, N'Орион', N'496-123 ', 2)
GO
SET IDENTITY_INSERT [dbo].[Provider] OFF
GO
ALTER TABLE [dbo].[Provider] ADD  CONSTRAINT [DF_Provider_City_id]  DEFAULT ((1)) FOR [City_id]
GO
ALTER TABLE [dbo].[Product_Provider]  WITH CHECK ADD  CONSTRAINT [FK_Product_Provider_Product] FOREIGN KEY([Product_id])
REFERENCES [dbo].[Product] ([Id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Product_Provider] CHECK CONSTRAINT [FK_Product_Provider_Product]
GO
ALTER TABLE [dbo].[Product_Provider]  WITH CHECK ADD  CONSTRAINT [FK_Product_Provider_Provider] FOREIGN KEY([Provider_id])
REFERENCES [dbo].[Provider] ([Id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Product_Provider] CHECK CONSTRAINT [FK_Product_Provider_Provider]
GO
ALTER TABLE [dbo].[Provider]  WITH CHECK ADD  CONSTRAINT [FK_Provider_City] FOREIGN KEY([City_id])
REFERENCES [dbo].[City] ([Id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Provider] CHECK CONSTRAINT [FK_Provider_City]
GO
USE [master]
GO
ALTER DATABASE [Variant8] SET  READ_WRITE 
GO
